#pragma config(Sensor, dgtl1,  Reset,          sensorTouch)
#pragma config(Sensor, dgtl2,  Pins,           sensorTouch)
#pragma config(Sensor, dgtl3,  M1,             sensorTouch)
#pragma config(Sensor, dgtl4,  M2,             sensorTouch)
#pragma config(Sensor, dgtl5,  M3,             sensorTouch)
#pragma config(Sensor, dgtl6,  M4,             sensorTouch)
#pragma config(Sensor, dgtl7,  M5,             sensorTouch)
#pragma config(Sensor, dgtl8,  LEDStrip,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, LED1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, LED2,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, LED4,           sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int score = 0; //Set Score as Variable

task main()
{
	while(true) //Set Infinite Loop
	{

		//Monster Count
		if(SensorValue(M1)==1) //If First Monster is Tapped
		{
			score++; //Add 1 to Score
			wait(1); //Delay for Count
		}
		if(SensorValue(M2)==1) //If Second Monster is Tapped
		{
			score++; //Add 1 to Score
			wait(1); //Delay for Count
		}
		if(SensorValue(M3)==1) //If Third Monster is Tapped
		{
			score++; //Add 1 to Score
			wait(1); //Delay for Count
		}
		if(SensorValue(M4)==1)//If Fourth Monster is Tapped
		{
			score++; //Add 1 to Score
			wait(1); //Delay for Count
		}
		if(SensorValue(M5)==1) //If Fifth Monster is Tapped
		{
			score++; //Add 1 to Score
			wait(1); //Delay for Count
		}

		//Touching Pin Ends Game
		if(SensorValue(Pins)==1) //If a Pin is fallen
		{
			turnLEDOn(LEDStrip);
			score++; //Add 1 to Score
			wait(1); //Delay for Count



			//Visual Score Count (Finish)
			if(score % 2 == 1) //If Score is Odd
			{
				turnLEDOn(LED1); //Turn First LED to set Visual Score Count
				score = score - 1; //Subtract from Digital Score Count to Make Even
			}

			if(score >= 4) //If Score is 4
			{
				turnLEDOn(LED4); //Turn Second LED to set Visual Score Count
				score = score - 4; //Subtract from Digital Score Count
			}

			if(score == 2) //If Score is 2
			{
				turnLEDOn(LED2); //Turn Third LED to set Visual Score Count
				score = score - 2; //Subtract from Digital Score Count to Make Even
			}

			//Restart The Game
			wait(10); //Delay
			turnLEDOff(LED4); //Turn Third LED Off
			turnLEDOff(LED2); //Turn Second LED Off
			turnLEDOff(LED1); //Turn First LED Off
			turnLEDOff(LEDStrip);
			score = 0; //Reset Score
		}
	}
}
